service: delete-old-dates
app: delete-old-dates-app
org: yeachan153

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.7
  region: eu-central-1
  deploymentBucket: fedex-case-serverless-deploy
  memorySize: 512
  environment:
    region: "eu-central-1"
    bucket_name: "fedex-case"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - arn:aws:s3:::fedex-case
        - arn:aws:s3:::fedex-case/*

functions:
  handler:
    handler: handler.delete
    timeout: 120
    reservedConcurrency: 50
